nginx-proxy:
  image: jwilder/nginx-proxy
  container_name: nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  restart: always
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /root/certs:/etc/nginx/certs:rw
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html
letsencrypt:
  image: jrcs/letsencrypt-nginx-proxy-companion:stable
  volumes: 
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /root/certs:/etc/nginx/certs:rw
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: 'always'
    io.rancher.sidekicks: nginx-proxy
  volumes_from: 
    - nginx-proxy