server:
  image: dockerepo/parse-server
  restart: always 
  environment: 
    - MONGO_DB_NAME=dev
    - APP_ID=X4jwAIMI2sCuH99ueEI4c8LdTbgnkrR4u5kSqsc8
    - MASTER_KEY=43p7s64k54z9uOKgztcC23CXx0cAM6RbdXObWfVt
  ports: 
    - "9001:1337"
  links: 
    - db:mongo
dashboard:
  image: dockerepo/parse-dashboard
  restart: always
  environment: 
    - PARSE_PUBLIC_ADDR=192.168.20.24
    - PARSE_PUBLIC_PORT=9001
    - APP_ID=X4jwAIMI2sCuH99ueEI4c8LdTbgnkrR4u5kSqsc8
    - MASTER_KEY=43p7s64k54z9uOKgztcC23CXx0cAM6RbdXObWfVt
  ports: 
    - "9000:4040" 
db:
  image: mongo
  ports: 
    - "27017:27017"