# server:
#   build: server
#   restart: always
#   volumes:
#     - ./server/server-config.json:/parse/server-config.json 
#   ports: 
#     - "8081:1337"
#   links: 
#     - db:mongo
#   command: server-config.json
# dashboard:
#   build: dashboard
#   restart: always
#   ports: 
#     - "8082:4040"
#   volumes:
#     - ./dashboard/dashboard-config.json:/dashboard/dashboard-config.json
#   links: 
#     - server:server
#   command: --config dashboard-config.json --allowInsecureHTTP true   
db:
  image: mongo
  ports: 
    - "27017:27017"
both:
  build: both
  links: 
    - db:mongo
  ports: 
    - "8084:4040"
    - "8083:1337"
  volumes:
    - ./both/dashboard-config.json:/parse/dashboard-config.json
    - ./both/server-config.json:/parse/server-config.json 