web:
  build: micro
  links: 
    - consul
  ports: 
    - "8082:8082"
  command: --registry_address=consul:8500 --register_interval=5 --register_ttl=10 web
consul:
  command: -server -bootstrap -rejoin 
  image: progrium/consul:latest
  ports:
  - "8500:8500"  
api:
  command: --registry_address=consul:8500 --register_interval=5 --register_ttl=10 api
  build: micro
  links:
  - consul
  ports:
  - "8080:8080"
sidecar:
  command: --registry_address=consul:8500 --register_interval=5 --register_ttl=10 sidecar
  build: micro
  links:
  - consul
  ports:
  - "8081:8081"