version: '2'

services:
  db:
    image: mysql:5.7
    ports:
     - "3306:3306"
    restart: always
    volumes:
      - mysql-prod:/var/lib/mysql
      - mysql-prod-conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: prod-secret-pw
      MYSQL_DATABASE: proddatabase
      MYSQL_USER: produser
      MYSQL_PASSWORD: prodpassword
volumes:
  mysql-prod: