version: '2'
services:
  db:
    image: mysql:5.5
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
volumes:
  mysql-data: