version: '2'

services:
  dind:
    image: docker:1.12.0-rc2-dind
    privileged: true
    ports: 
      - "2377:2377"
    volumes: 
      - data:/var/lib/docker
    container_name: dind
  client:
    image: docker:1.12.0-rc2
    links: 
      - dind:docker
    command: version
volumes:
  data:
    external:
      name: docker-data